#server:
#  port: 8080
#spring:
#  application:
#    name: compcany-frame
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      url: jdbc:mysql://gz-cdb-8eb31bl9.sql.tencentcdb.com:62217/company_frame?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: ljr33220
#      driver-class-name: com.mysql.jdbc.Driver
#
################### 连接池配置 ################ #连接池建立时创建的初始化连接数
#      initial-size: 5
##连接池中最大的活跃连接数
#      max-active: 20
##连接池中最小的活跃连接数
#      min-idle: 5
## 配置获取连接等待超时的时间
#      max-wait: 60000
#      max-pool-prepared-statement-per-connection-size: 20
## 打开PSCache，并且指定每个连接上PSCache的大小
#      pool-prepared-statements: true
#      validation-query: SELECT 1 FROM DUAL
#      query-timeout: 30000
##是否在获得连接后检测其可用性
#      test-on-borrow: false
##是否在连接放回连接池后检测其可用性
#      test-on-return: false
##是否在连接空闲一段时间后检测其可用性
#      test-while-idle: true
## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
## 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
## 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filter: stat,wall
##设置监控页面的登录名和密码
#      stat-view-servlet:
#        login-username: admin
#        login-password: 666666
#
##logging配置 logging:
#file: ${logging.path}/${spring.application.name}.log
#path: logs
#level:
#  com.linjr: debug
##加入以下配置 对应生成 mapper.xml 的路径
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#
##swagger 开关 swagger2:
#enable: true
#
##redis配置开始
#redis:
## Redis服务器地址
#host: localhost
## Redis服务器连接端口
#port: 6379 #Redis服务器连接密码(默认为空) #password:
#lettuce:
#pool:
## 连接池最大连接数(使用负值表示没有限制) max-active: 1024
## 连接池最大阻塞等待时间(使用负值表示没有限制)10秒 max-wait: PT10S
## 连接池中的最大空闲连接
#max-idle: 200
## 连接池中的最小空闲连接
#min-idle: 0
## 连接超时时间(10秒) timeout: PT10S
#JWT 密钥 jwt:
#secretKey: 78944878877848fg) accessTokenExpireTime: PT2H refreshTokenExpireTime: PT8H refreshTokenExpireAppTime:P30D issuer: yingxue.org.cn